# https://developers.cloudflare.com/workers/cli-wrangler/configuration

name = "url-shortener"
type = "javascript"
account_id = "75ed923ff0a66b8294368448841bb028"
zone_id = ""
route = ""
workers_dev = true

kv_namespaces = [
  { binding = "URL_SHORTENER", id = "86d32a6ff93046a0b4cb0748db477915", preview_id = "1f686100cc6b403e85f0a01cb12d34b2" }
]

[build]
upload.format = "service-worker"
command = "lerna bootstrap && npm run build"
