# https://developers.cloudflare.com/workers/cli-wrangler/configuration

name = "url-shortener"
type = "javascript"
account_id = ""
zone_id = ""
route = ""
workers_dev = true

[build]
upload.format = "service-worker"
command = "yarn install && yarn build"
